Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  copyright: 
  #analytics: UA-YOURCODE
  basedir: "/Users/err8n/p/neatline/omeka/plugins"
  repos:
    - Neatline
    - NeatlineFeatures
    - NeatlineMaps
    - NeatlineTime

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  #approot: "http://www.example.com"
  <<: *defaults
  basedir: "/tmp"
