Default: &defaults
  database: NeatlineUpdate.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: NeatlineUpdate_test.sqlite3
  <<: *defaults

Staging:
  database: NeatlineUpdate_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: NeatlineUpdate_production.sqlite3
  poolsize: 100
  <<: *defaults
